core.entity_form_display.group.flexible_group.default:
  expected_config: { }
  update_actions:
    add:
      third_party_settings:
        field_group:
          group_personalisation:
            children:
              - field_group_posts_enabled
            format_settings:
              classes: ''
              description: ''
              id: ''
              required_fields: true
            format_type: fieldset
            label: 'Personalisation'
            parent_name: ''
            region: content
            weight: 1
      content:
        field_group_posts_enabled:
          weight: 99
          settings:
            display_label: true
          third_party_settings: { }
          type: boolean_checkbox
          region: content
    change:
      third_party_settings:
        field_group:
          group_access_permissions:
            weight: 2
          group_location:
            weight: 3
          group_additional_details:
            weight: 4
          group_settings:
            weight: 5
