field.storage.group.field_group_allowed_join_method:
  expected_config:
    settings:
      allowed_values:
        -
          value: direct
          label: 'Join directly'
        -
          value: added
          label: 'Be added'
      allowed_values_function: ''
  update_actions:
    change:
      settings:
        allowed_values: {  }
        allowed_values_function: '_social_group_allowed_values_callback'
