social_comment.comment_settings:
  type: config_object
  label: 'Social Comment Settings'
  mapping:
    redirect_comment_to_entity:
      type: boolean
      label: 'Redirect a comment view to its parent entity'
    remove_author_field:
      type: boolean
      label: 'Whether the author field should be removed from comment forms.'

views.filter.filter_by_group:
  type: views.filter.in_operator
  label: 'Filter by group'

views.relationship.group_content:
  type: views_relationship_with_group_plugin_filter
  label: 'Group relationship'
