core.entity_view_display.profile.profile.preview:
  expected_config:
    content:
      uid:
        type: entity_reference_label
  update_actions:
    change:
      content:
        uid:
          type: social_profile_preview_username
