core.entity_view_display.profile.profile.preview:
  expected_config: { }
  update_actions:
    delete:
      content:
        social_follow_user: {  }
    add:
      content:
        followers:
          weight: 5
          region: content
          settings: {  }
          third_party_settings: {  }
        following:
          weight: 6
          region: content
          settings: {  }
          third_party_settings: {  }
