social_event_type.settings:
  type: config_object
  label: 'Social Event Type settings'
  mapping:
    social_event_type_required:
      type: boolean
      label: 'Whether the type selection is required for events.'
    social_event_type_select_changer:
      type: integer
      label: 'At what number of event types to switch from radio buttons to select widget.'
