core.entity_view_display.profile.profile.teaser:
  expected_config:
    hidden:
      field_profile_self_introduction: true
      field_profile_summary: true
  update_actions:
    delete:
      hidden:
        field_profile_self_introduction: true
        field_profile_summary: true
    add:
      content:
        field_profile_self_introduction:
          type: social_profile_text
          weight: 6
          region: content
          label: hidden
          settings:
            trim_length: 140
          third_party_settings: {  }
        field_profile_summary:
          type: string
          weight: 7
          region: content
          label: hidden
          settings:
            link_to_entity: false
          third_party_settings: {  }
