core.entity_form_display.profile.profile.default:
  expected_config: {  }
  update_actions:
    add:
      third_party_settings:
        field_group:
          group_profile_self_intro:
            children:
              field_profile_summary: field_profile_summary
      content:
        field_profile_summary:
          weight: 11
          settings:
            size: 140
            placeholder: ''
          third_party_settings: {  }
          type: social_profile_string_textarea
          region: content
