core.entity_view_display.profile.profile.compact:
  expected_config:
    content:
      field_profile_image:
        weight: 7
        settings:
          image_link: ''
        type: image
  update_actions:
    change:
      content:
        field_profile_image:
          weight: 0
          settings:
            image_link: owner
          type: social_profile_avatar
