# Schema for the configuration files of the social_emojis module.

field.widget.settings.string_textarea.third_party.social_emoji:
  type: mapping
  label: 'Social emoji settings'
  mapping:
    display_emoji_picker:
      type: boolean
      label: 'Display emoji picker'

field.widget.settings.text_textarea.third_party.social_emoji:
  type: mapping
  label: 'Social emoji settings'
  mapping:
    display_emoji_picker:
      type: boolean
      label: 'Display emoji picker'

field.widget.settings.text_textarea_with_summary.third_party.social_emoji:
  type: mapping
  label: 'Social emoji settings'
  mapping:
    display_emoji_picker:
      type: boolean
      label: 'Display emoji picker'
