# Schema for the configuration files of the Gin theme.
gin.settings:
  type: theme_settings
  label: 'gin settings'
  mapping:
    preset_accent_color:
      type: string
      label: 'Preset accent color'
    preset_focus_color:
      type: string
      label: 'Preset focus color'
    enable_darkmode:
      type: string
      label: 'The darkmode'
    classic_toolbar:
      type: string
      label: 'The classic toolbar'
    secondary_toolbar_frontend:
      type: boolean
      label: 'Secondary toolbar in Frontend'
    high_contrast_mode:
      type: boolean
      label: 'High contrast mode'
    accent_color:
      type: string
      label: 'The accent color'
    focus_color:
      type: string
      label: 'The focus color'
    show_description_toggle:
      type: boolean
      label: 'Display help icon to toggle form description'
    show_user_theme_settings:
      type: boolean
      label: 'Let user override theme'
    third_party_settings:
      type: mapping
      label: 'Third party settings'
      mapping:
        shortcut:
          type: mapping
          label: 'Shortcut'
          mapping:
            module_link:
              type: boolean
              label: 'Module Link'
