views.view.social_group_invitations:
  expected_config: { }
  update_actions:
    delete:
      display:
        default:
          display_options:
            access:
              options:
                group_permission: { }
            fields:
              delete_group_content: { }
              dropbutton: { }
    change:
      display:
        default:
          display_options:
            access:
              type: group_managers_only
              options: {  }
    add:
      display:
        default:
          display_options:
            fields:
              social_views_bulk_operations_bulk_form_invites:
                id: social_views_bulk_operations_bulk_form_invites
                table: views
                field: social_views_bulk_operations_bulk_form_invites
                relationship: none
                group_type: group
                admin_label: ''
                label: ''
                exclude: false
                alter:
                  alter_text: false
                  text: ''
                  make_link: false
                  path: ''
                  absolute: false
                  external: false
                  replace_spaces: false
                  path_case: none
                  trim_whitespace: false
                  alt: ''
                  rel: ''
                  link_class: ''
                  prefix: ''
                  suffix: ''
                  target: ''
                  nl2br: false
                  max_length: 0
                  word_boundary: true
                  ellipsis: true
                  more_link: false
                  more_link_text: ''
                  more_link_path: ''
                  strip_tags: false
                  trim: false
                  preserve_tags: ''
                  html: false
                element_type: ''
                element_class: views-field-views-bulk-operations-bulk-form
                element_label_type: ''
                element_label_class: ''
                element_label_colon: false
                element_wrapper_type: ''
                element_wrapper_class: ''
                element_default_classes: true
                empty: ''
                hide_empty: false
                empty_zero: false
                hide_alter_empty: true
                batch: 1
                batch_size: '10'
                form_step: true
                buttons: 0
                clear_on_exposed: 0
                action_title: Action
                selected_actions:
                  0:
                    action_id: social_group_invite_resend_action
                    preconfiguration:
                      label_override: 'Send reminders'
                  3:
                    action_id: social_group_delete_group_content_action
                    preconfiguration:
                      label_override: 'Remove invites'
                force_selection_info: 0
                plugin_id: social_views_bulk_operations_bulk_form_invites
              operations:
                id: operations
                table: group_content
                field: operations
                relationship: none
                group_type: group
                admin_label: ''
                label: Operations
                exclude: false
                alter:
                  alter_text: false
                  text: ''
                  make_link: false
                  path: ''
                  absolute: false
                  external: false
                  replace_spaces: false
                  path_case: none
                  trim_whitespace: false
                  alt: ''
                  rel: ''
                  link_class: ''
                  prefix: ''
                  suffix: ''
                  target: ''
                  nl2br: false
                  max_length: 0
                  word_boundary: true
                  ellipsis: true
                  more_link: false
                  more_link_text: ''
                  more_link_path: ''
                  strip_tags: false
                  trim: false
                  preserve_tags: ''
                  html: false
                element_type: ''
                element_class: ''
                element_label_type: ''
                element_label_class: ''
                element_label_colon: true
                element_wrapper_type: ''
                element_wrapper_class: ''
                element_default_classes: true
                empty: ''
                hide_empty: false
                empty_zero: false
                hide_alter_empty: true
                destination: true
                entity_type: group_content
                plugin_id: entity_operations
