core.entity_form_display.node.event.default:
  expected_config: { }
  update_actions:
    add:
      content:
        field_event_send_confirmation:
          weight: 126
          settings:
            display_label: true
          third_party_settings: { }
          type: boolean_checkbox
          region: content
