version: "3"

services:
  drupal8:
    image: mkeereman/drupal8_tests:8.7
    ports:
      - "8081:80"
    volumes:
      - ./:/app
    networks:
      bef:

  mariadb-host:
    image: mariadb:10.3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3309:3306"
    networks:
      bef:

  chrome:
    image: selenium/standalone-chrome-debug:3.14.0-beryllium
    ports:
      - "4444:4444"
      - "32771:5900"
    networks:
      bef:

networks:
  bef:
    driver: bridge
