<?php

/**
 * @file
 * Enables Group functionality for the Node module.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Session\AccountInterface;
use Drupal\group\Entity\GroupContentType;
use Drupal\group\Entity\GroupRoleInterface;
use Drupal\node\NodeInterface;
use Drupal\node\NodeTypeInterface;

// We need a grant ID for match-all access records.
define('GNODE_MASTER_GRANT_ID', 1986);

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function gnode_node_type_insert(NodeTypeInterface $node_type) {
  \Drupal::service('plugin.manager.group_content_enabler')->clearCachedDefinitions();
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function gnode_group_role_insert(GroupRoleInterface $group_role) {
  // Because we optimize for anonymous users, it also means we need to rebuild
  // the node grants table when an anonymous role is added.
  // See: gnode_node_access_records()
  if ($group_role->isAnonymous()) {
    node_access_needs_rebuild(TRUE);
  }
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function gnode_group_role_update(GroupRoleInterface $group_role) {
  // Because we optimize for anonymous users, it also means we need to rebuild
  // the node grants table when an anonymous role has its permissions changed.
  // See: gnode_node_access_records()
  if ($group_role->isAnonymous()) {
    $new = array_unique($group_role->getPermissions());
    $old = array_unique($group_role->original->getPermissions());
    sort($new);
    sort($old);

    if ($new != $old) {
      node_access_needs_rebuild(TRUE);
    }
  }
}

/**
 * Implements hook_node_access().
 *
 * When trying to view, update or delete a node it suffices to have the right to
 * do so in only one group the node belongs to. If you wish to prevent any such
 * action on your own terms, implement hook_node_access() in your module.
 */
function gnode_node_access(NodeInterface $node, $op, AccountInterface $account) {
  // We do not care about create access as we have our own wizard for that. Any
  // operation aside from 'view', 'update' and 'delete' is also unsupported.
  if (!in_array($op, ['view', 'update', 'delete'])) {
    return AccessResult::neutral();
  }

  // Some modules, including the code in \Drupal\node\NodeForm::access() may
  // check for 'view', 'update' or 'delete' access on new nodes, even though
  // that makes little sense. We need to account for it to avoid crashes because
  // we would otherwise query the DB with a non-existent node ID.
  if ($node->isNew()) {
    return AccessResult::neutral();
  }

  $plugin_id = 'group_node:' . $node->bundle();

  // Only act if there are group content types for this node type.
  $group_content_types = GroupContentType::loadByContentPluginId($plugin_id);
  if (empty($group_content_types)) {
    return AccessResult::neutral();
  }

  // Load all the group content for this node.
  $group_contents = \Drupal::entityTypeManager()
    ->getStorage('group_content')
    ->loadByProperties([
      'type' => array_keys($group_content_types),
      'entity_id' => $node->id(),
    ]);

  // If the node does not belong to any group, we have nothing to say.
  if (empty($group_contents)) {
    return AccessResult::neutral();
  }

  /** @var \Drupal\group\Entity\GroupInterface[] $groups */
  $groups = [];
  foreach ($group_contents as $group_content) {
    /** @var \Drupal\group\Entity\GroupContentInterface $group_content */
    $group = $group_content->getGroup();
    $groups[$group->id()] = $group;
  }

  // From this point on you need group to allow you to perform the operation.
  switch ($op) {
    case 'view':
      foreach ($groups as $group) {
        if ($node->isPublished()) {
          if ($group->hasPermission("view $plugin_id entity", $account)) {
            return AccessResult::allowed();
          }
        }
        elseif ($group->hasPermission("view unpublished $plugin_id entity", $account)) {
          return AccessResult::allowed();
        }
      }
      break;

    case 'update':
    case 'delete':
      foreach ($groups as $group) {
        if ($group->hasPermission("$op any $plugin_id entity", $account)) {
          return AccessResult::allowed();
        }
        elseif ($account->id() == $node->getOwnerId() && $group->hasPermission("$op own $plugin_id entity", $account)) {
          return AccessResult::allowed();
        }
      }
      break;
  }

  // Instead of outright forbidding access when no group granted it, we return
  // a neutral access result to play nice with other modules. If the end result
  // is still neutral, Drupal will deny access anyway unless the node grants
  // system allows the operation in a last ditch effort to determine access.
  return AccessResult::neutral();
}

/**
 * Implements hook_node_grants().
 *
 * We define the following grants:
 * - 'gnode:NODE_TYPE': Grants view and update or delete any access to nodes.
 * - 'gnode_unpublished:NODE_TYPE': Grants view access to unpublished nodes.
 * - 'gnode_author:UID:NODE_TYPE': Grants update or delete access to authors.
 * - 'gnode_anonymous': Given to anonymous users.
 * - 'gnode_bypass': Given to anyone with the 'bypass group access' permission.
 *
 * @see gnode_node_access_records()
 */
function gnode_node_grants(AccountInterface $account, $op) {
  // Provide the master grant for users who can bypass group access.
  if ($account->hasPermission('bypass group access')) {
    return ['gnode_bypass' => [GNODE_MASTER_GRANT_ID]];
  }

  // Anonymous users get the anonymous grant. See the implementation in the
  // gnode_node_access_records() function as to why that is.
  if ($account->isAnonymous()) {
    return ['gnode_anonymous' => [GNODE_MASTER_GRANT_ID]];
  }

  // Gather the machine names of all node types.
  $entity_type_manager = \Drupal::entityTypeManager();
  $node_type_ids = $entity_type_manager
    ->getStorage('node_type')
    ->getQuery()
    ->execute();

  // Initialize a grant array for members and one for outsider users.
  $grants_m = $grants_o = [];

  // If the user could not bypass group access, we need to check their access
  // for every single group. Because loading every group would incur a massive
  // performance hit, we only load those groups the user is a member of.
  /** @var \Drupal\group\GroupMembershipLoaderInterface $membership_loader */
  $membership_loader = \Drupal::service('group.membership_loader');
  foreach ($membership_loader->loadByUser($account) as $group_membership) {
    $group = $group_membership->getGroup();

    // Add the groups the user is a member of to use later on.
    $member_gids[] = $gid = $group->id();

    foreach ($node_type_ids as $node_type_id) {
      $plugin_id = "group_node:$node_type_id";

      switch ($op) {
        case 'view':
          if ($group->hasPermission("view $plugin_id entity", $account)) {
            $grants_m["gnode:$node_type_id"][] = $gid;
          }
          if ($group->hasPermission("view unpublished $plugin_id entity", $account)) {
            $grants_m["gnode_unpublished:$node_type_id"][] = $gid;
          }
          break;

        case 'update':
        case 'delete':
          // If you can act on any node, there's no need for the author grant.
          if ($group->hasPermission("$op any $plugin_id entity", $account)) {
            $grants_m["gnode:$node_type_id"][] = $gid;
          }
          elseif ($group->hasPermission("$op own $plugin_id entity", $account)) {
            $uid = $account->id();
            $grants_m["gnode_author:$uid:$node_type_id"][] = $gid;
          }
          break;
      }
    }
  }

  // All other groups have the benefit of sharing the same permission set among
  // all authenticated users per group type. We can therefore know the user's
  // permissions for all groups of the same group type they aren't part of.
  /** @var \Drupal\group\Entity\GroupTypeInterface[] $group_types */
  $group_types = $entity_type_manager->getStorage('group_type')->loadMultiple();
  foreach ($group_types as $group_type) {
    // Get the IDs of all the groups the user is not part of for the group type.
    $query = $entity_type_manager->getStorage('group')->getQuery();
    $query->condition('type', $group_type->id());
    if (!empty($member_gids)) {
      $query->condition('id', $member_gids, 'NOT IN');
    }
    $gids = $query->execute();

    // If we could not retrieve any group IDs, skip to the next group type.
    if (empty($gids)) {
      continue;
    }

    // Grab the outsider role for the group type.
    $group_role = $group_type->getOutsiderRole();

    foreach ($node_type_ids as $node_type_id) {
      $plugin_id = "group_node:$node_type_id";

      // Only check for permissions if the group type has the group_node plugin
      // installed for the node type.
      if (!$group_type->hasContentPlugin($plugin_id)) {
        continue;
      }

      switch ($op) {
        case 'view':
          if ($group_role->hasPermission("view $plugin_id entity")) {
            $grants_o["gnode:$node_type_id"][] = $gids;
          }
          if ($group_role->hasPermission("view unpublished $plugin_id entity")) {
            $grants_o["gnode_unpublished:$node_type_id"][] = $gids;
          }
          break;

        case 'update':
        case 'delete':
          // If you can act on any node, there's no need for the author grant.
          if ($group_role->hasPermission("$op any $plugin_id entity")) {
            $grants_o["gnode:$node_type_id"][] = $gids;
          }
          elseif ($group_role->hasPermission("$op own $plugin_id entity")) {
            $uid = $account->id();
            $grants_o["gnode_author:$uid:$node_type_id"][] = $gids;
          }
          break;
      }
    }
  }

  // The code above populated the outsider grants by adding the group IDs per
  // group type. We need to combine this into one big list of group IDs per
  // entry in the $grants_o array.
  foreach ($grants_o as $key => $gids_per_group_type) {
    $grants_o[$key] = array_reduce($gids_per_group_type, 'array_merge', []);
  }

  // Recursively merge the member grants with the outsider grants.
  return array_merge_recursive($grants_m, $grants_o);
}

/**
 * Implements hook_node_access_records().
 *
 * @see gnode_node_grants()
 */
function gnode_node_access_records(NodeInterface $node) {
  $records = $group_types = [];
  $node_type_id = $node->bundle();
  $plugin_id = "group_node:$node_type_id";

  // Only act if there are group content types for this node type.
  $group_content_types = GroupContentType::loadByContentPluginId($plugin_id);
  if (empty($group_content_types)) {
    return $records;
  }

  // Load all of the group content for this node.
  $group_contents = \Drupal::entityTypeManager()
    ->getStorage('group_content')
    ->loadByProperties([
      'type' => array_keys($group_content_types),
      'entity_id' => $node->id()
    ]);

  // Only act if there are group content entities for this node.
  if (empty($group_contents)) {
    return $records;
  }

  // We can use the same grant-all base because we will only hand out the grants
  // based on the $op parameter in hook_node_grants().
  $base = [
    'grant_view' => 1,
    'grant_update' => 1,
    'grant_delete' => 1,
    'priority' => 0,
  ];

  // Set records for every group the node belongs to.
  $uid = $node->getOwnerId();
  $prefix = $node->isPublished() ? 'gnode' : 'gnode_unpublished';
  foreach ($group_contents as $group_content) {
    /** @var \Drupal\group\Entity\GroupContentInterface $group_content */
    $group = $group_content->getGroup();
    $group_type_id = $group_content->bundle();

    // Gather all group types the node belongs to.
    if (!isset($group_types[$group_type_id])) {
      $group_types[$group_type_id] = $group->getGroupType();
    }

    // We use the group ID as the realm ID.
    $gid = $group->id();

    // Add the non-author record for viewing nodes.
    $records[] = ['gid' => $gid, 'realm' => "$prefix:$node_type_id"] + $base;

    // Add the author record for updating or deleting.
    $records[] = ['gid' => $gid, 'realm' => "gnode_author:$uid:$node_type_id"] + $base;
  }

  // Add the general access bypass record.
  $records[] = ['gid' => GNODE_MASTER_GRANT_ID, 'realm' => 'gnode_bypass'] + $base;

  // For anonymous users we actually build the access record based on the groups
  // the node belongs to. After all: If you're anonymous to one group, you're
  // anonymous to all groups. Meaning that if one of the node's groups allows
  // anonymous users to view the node, all anonymous users can view it. We can
  // use this to our advantage by assigning a special access record that we can
  // provide a grant for in gnode_node_grants().
  $anonymous_record = [
    'gid' => GNODE_MASTER_GRANT_ID,
    'realm' => 'gnode_anonymous',
    'grant_view' => 0,
    'grant_update' => 0,
    'grant_delete' => 0,
    'priority' => 0,
  ];

  // Get references to the grants for faster and more readable loops below.
  $can_view = &$anonymous_record['grant_view'];
  $can_update = &$anonymous_record['grant_update'];
  $can_delete = &$anonymous_record['grant_delete'];

  $view_permission = $node->isPublished()
    ? "view $plugin_id entity"
    : "view unpublished $plugin_id entity";

  foreach ($group_types as $group_type) {
    /** @var \Drupal\group\Entity\GroupTypeInterface $group_type */
    $group_role = $group_type->getAnonymousRole();

    if (!$can_view && $group_role->hasPermission($view_permission)) {
      $can_view = 1;
    }
    if (!$can_update && $group_role->hasPermission("update any $plugin_id entity")) {
      $can_update = 1;
    }
    if (!$can_delete && $group_role->hasPermission("delete any $plugin_id entity")) {
      $can_delete = 1;
    }

    // If the node is owned by anonymous, we also need to check for the author
    // permissions following the pattern "$op own $plugin_id entity".
    if ($uid == 0) {
      if (!$can_update && $group_role->hasPermission("update own $plugin_id entity")) {
        $can_update = 1;
      }
      if (!$can_delete && $group_role->hasPermission("delete own $plugin_id entity")) {
        $can_delete = 1;
      }
    }
  }

  $records[] = $anonymous_record;

  return $records;
}
