views.view.user_admin_people:
  expected_config:
    display:
      default:
        display_options:
          filters:
            id:
              expose:
                max_placeholder: ''
                min_placeholder: ''
                multiple: false
                placeholder: ''
              group_info:
                description: null
                group_items:
                  1: {  }
                  2: {  }
                  3: {  }
                identifier: id
                label: ID
              operator: '='
              plugin_id: numeric
              value:
                max: ''
                min: ''
                value: ''
  update_actions:
    delete:
      display:
        default:
          display_options:
            filters:
              id:
                expose:
                  max_placeholder: ''
                  min_placeholder: ''
                  placeholder: ''
                group_info:
                  group_items:
                    1: {  }
                    2: {  }
                    3: {  }
                value:
                  max: ''
                  min: ''
                  value: ''
    add:
      display:
        default:
          display_options:
            filters:
              id:
                expose:
                  remember_roles:
                    verified: '0'
    change:
      display:
        default:
          display_options:
            filters:
              id:
                expose:
                  multiple: true
                  reduce: false
                group_info:
                  description: ''
                  group_items: {  }
                  identifier: ''
                  label: ''
                operator: in
                plugin_id: in_operator
                value: {  }
