views.view.group_topics:
  expected_config: {  }
  update_actions:
    add:
      display:
        default:
          display_options:
            filters:
              default_langcode:
                admin_label: ''
                entity_field: default_langcode
                entity_type: node
                expose:
                  description: ''
                  identifier: ''
                  label: ''
                  multiple: false
                  operator: ''
                  operator_id: ''
                  operator_limit_selection: false
                  operator_list: { }
                  remember: false
                  remember_roles:
                    authenticated: authenticated
                  required: false
                  use_operator: false
                exposed: false
                field: default_langcode
                group: 1
                group_info:
                  default_group: All
                  default_group_multiple: { }
                  description: ''
                  group_items: { }
                  identifier: ''
                  label: ''
                  multiple: false
                  optional: true
                  remember: false
                  widget: select
                group_type: group
                id: default_langcode
                is_grouped: false
                operator: '='
                plugin_id: boolean
                relationship: gc__node
                table: node_field_data
                value: '1'
        page_group_topics:
          display_options:
            rendering_language: '***LANGUAGE_language_interface***'
