views.view.followers_user:
  expected_config:
    display:
      default:
        display_options:
          title: Followers
  update_actions:
    change:
      display:
        default:
          display_options:
            title: ''
