message.template.create_comment_community_node:
  expected_config:
    third_party_settings:
      activity_logger:
        activity_aggregate: true
        activity_create_direct: true
  update_actions:
    change:
      third_party_settings:
        activity_logger:
          activity_aggregate: 1
          activity_create_direct: 1
message.template.create_comment_community_post:
  expected_config:
    settings:
      purge_methods: {  }
    third_party_settings:
      activity_logger:
        activity_aggregate: true
        activity_create_direct: true
  update_actions:
    delete:
      settings:
        purge_methods: {  }
    change:
      settings:
        purge:
          days: null
          enabled: false
          override: false
          quota: null
      third_party_settings:
        activity_logger:
          activity_aggregate: 1
          activity_create_direct: 1
message.template.create_comment_group_node:
  expected_config:
    third_party_settings:
      activity_logger:
        activity_aggregate: true
        activity_create_direct: true
  update_actions:
    change:
      third_party_settings:
        activity_logger:
          activity_aggregate: 1
          activity_create_direct: 1
message.template.create_comment_group_post:
  expected_config:
    settings:
      purge_methods: {  }
    third_party_settings:
      activity_logger:
        activity_aggregate: true
        activity_create_direct: true
  update_actions:
    delete:
      settings:
        purge_methods: {  }
    change:
      settings:
        purge:
          days: null
          enabled: false
          override: false
          quota: null
      third_party_settings:
        activity_logger:
          activity_aggregate: 1
          activity_create_direct: 1
message.template.create_event_community:
  expected_config:
    settings:
      purge_methods: {  }
    third_party_settings:
      activity_logger:
        activity_create_direct: false
  update_actions:
    delete:
      settings:
        purge_methods: {  }
    change:
      settings:
        purge:
          days: null
          enabled: false
          override: false
          quota: null
      third_party_settings:
        activity_logger:
          activity_create_direct: 0
message.template.create_event_group:
  expected_config:
    third_party_settings:
      activity_logger:
        activity_create_direct: false
  update_actions:
    change:
      third_party_settings:
        activity_logger:
          activity_create_direct: 0
message.template.create_post_community:
  expected_config:
    settings:
      purge_methods: {  }
    third_party_settings:
      activity_logger:
        activity_create_direct: true
  update_actions:
    delete:
      settings:
        purge_methods: {  }
    change:
      settings:
        purge:
          days: null
          enabled: false
          override: false
          quota: null
      third_party_settings:
        activity_logger:
          activity_create_direct: 1
message.template.create_post_group:
  expected_config:
    settings:
      purge_methods: {  }
    third_party_settings:
      activity_logger:
        activity_create_direct: true
  update_actions:
    delete:
      settings:
        purge_methods: {  }
    change:
      settings:
        purge:
          days: null
          enabled: false
          override: false
          quota: null
      third_party_settings:
        activity_logger:
          activity_create_direct: 1
message.template.create_post_profile_stream:
  expected_config:
    settings:
      purge_methods: {  }
    third_party_settings:
      activity_logger:
        activity_aggregate: false
        activity_create_direct: true
  update_actions:
    delete:
      settings:
        purge_methods: {  }
    change:
      settings:
        purge:
          days: null
          enabled: false
          override: false
          quota: null
      third_party_settings:
        activity_logger:
          activity_aggregate: 0
          activity_create_direct: 1
message.template.create_topic_community:
  expected_config:
    settings:
      purge_methods: {  }
    third_party_settings:
      activity_logger:
        activity_create_direct: false
  update_actions:
    delete:
      settings:
        purge_methods: {  }
    change:
      settings:
        purge:
          days: null
          enabled: false
          override: false
          quota: null
      third_party_settings:
        activity_logger:
          activity_create_direct: 0
message.template.create_topic_group:
  expected_config:
    third_party_settings:
      activity_logger:
        activity_create_direct: false
  update_actions:
    change:
      third_party_settings:
        activity_logger:
          activity_create_direct: 0
message.template.moved_content_between_groups:
  expected_config:
    third_party_settings:
      activity_logger:
        activity_aggregate: false
        activity_create_direct: true
  update_actions:
    change:
      third_party_settings:
        activity_logger:
          activity_aggregate: 0
          activity_create_direct: 1
