views.view.activity_stream:
  expected_config: {  }
  update_actions:
    add:
      display:
        block_stream_explore:
          display_plugin: block
          id: block_stream_explore
          display_title: 'Explore Stream Block'
          position: 5
          display_options:
            display_extenders: {  }
            filters:
              field_activity_destinations_value:
                id: field_activity_destinations_value
                table: activity__field_activity_destinations
                field: field_activity_destinations_value
                relationship: none
                group_type: group
                admin_label: ''
                operator: or
                value:
                  stream_explore: stream_explore
                group: 1
                exposed: false
                expose:
                  operator_id: ''
                  label: ''
                  description: ''
                  use_operator: false
                  operator: ''
                  operator_limit_selection: false
                  operator_list: {  }
                  identifier: ''
                  required: false
                  remember: false
                  multiple: false
                  remember_roles:
                    authenticated: authenticated
                  reduce: false
                is_grouped: false
                group_info:
                  label: ''
                  description: ''
                  identifier: ''
                  optional: true
                  widget: select
                  multiple: false
                  remember: false
                  default_group: All
                  default_group_multiple: {  }
                  group_items: {  }
                reduce_duplicates: false
                plugin_id: list_field
              activity_post_visibility_access_filter:
                id: activity_post_visibility_access_filter
                table: activity
                field: activity_post_visibility_access_filter
                relationship: none
                group_type: group
                admin_label: ''
                operator: '='
                value: ''
                group: 1
                exposed: false
                expose:
                  operator_id: ''
                  label: ''
                  description: ''
                  use_operator: false
                  operator: ''
                  operator_limit_selection: false
                  operator_list: {  }
                  identifier: ''
                  required: false
                  remember: false
                  multiple: false
                  remember_roles:
                    authenticated: authenticated
                is_grouped: false
                group_info:
                  label: ''
                  description: ''
                  identifier: ''
                  optional: true
                  widget: select
                  multiple: false
                  remember: false
                  default_group: All
                  default_group_multiple: {  }
                  group_items: {  }
                entity_type: activity
                plugin_id: activity_post_visibility_access
            defaults:
              filters: false
              filter_groups: false
              title: false
              header: false
            filter_groups:
              operator: AND
              groups:
                1: AND
            title: Stream
            display_description: ''
            header: {  }
          cache_metadata:
            max-age: -1
            contexts:
              - 'languages:language_interface'
              - url.query_args
            tags:
              - 'config:core.entity_view_display.activity.activity.default'
              - 'config:core.entity_view_display.activity.activity.notification'
              - 'config:core.entity_view_display.activity.activity.notification_archive'
