message.template.create_mention_comment_stream:
  expected_config:
    third_party_settings:
      activity_logger:
        activity_aggregate: false
        activity_create_direct: true
  update_actions:
    change:
      third_party_settings:
        activity_logger:
          activity_aggregate: 0
          activity_create_direct: 1
message.template.create_mention_post_stream:
  expected_config:
    third_party_settings:
      activity_logger:
        activity_aggregate: false
        activity_create_direct: true
  update_actions:
    change:
      third_party_settings:
        activity_logger:
          activity_aggregate: 0
          activity_create_direct: 1
