social_event_managers.settings:
  type: config_object
  label: 'Social Event Managers Settings'
  mapping:
    author_as_manager:
      type: bool
      label: 'Whether the author of an event is automatically an event organiser.'
