metatag.metatag_defaults.group_content__closed_group-group_node-event:
  expected_config: {  }
  update_actions:
    change:
      tags:
        og_street_address: '[node:field_event_address:address_line1]'
metatag.metatag_defaults.node__event:
  expected_config: {  }
  update_actions:
    change:
      tags:
        og_street_address: '[node:field_event_address:address_line1]'
