name: Mirror to drupal.org
on: [ push ]
jobs:
  git-mirror:
    runs-on: ubuntu-latest
    environment: mirror
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source-repo: 'https://github.com/drupal-graphql/graphql.git'
          destination-repo: 'git@git.drupal.org:project/graphql.git'
