group_content_enabler.config.invitation_expire:
  type: 'integer'
  label: 'Expire invites'

group_content_enabler.config.invitation_subject:
  type: 'text'
  label: 'Subject'

group_content_enabler.config.invitation_body:
  type: 'text'
  label: 'Body'

group_content_enabler.config.existing_user_invitation_subject:
  type: 'text'
  label: 'Subject'

group_content_enabler.config.existing_user_invitation_body:
  type: 'text'
  label: 'Body'

group_content_enabler.config.unblock_invitees:
  type: 'boolean'
  label: 'Unblock invitees'

group_content_enabler.config.invitation_bypass_form:
  type: 'boolean'
  label: 'Accept invitations immediately'

group_content_enabler.config.cancel_user_invitation_subject:
  type: 'text'
  label: 'Subject'

group_content_enabler.config.cancel_user_invitation_body:
  type: 'text'
  label: 'Body'

group_content_enabler.config.send_cancel_email:
  type: 'boolean'
  label: 'Send notification when an invitation is cancelled'

group_content_enabler.config.send_email_existing_users:
  type: 'boolean'
  label: 'Send invitation e-mail to already registered users'
