social_event_an_enroll.settings:
  type: config_object
  label: 'Social Event Anonymous Enrollment Settings'
  mapping:
    event_an_enroll:
      type: bool
      label: 'Whether event enrollment for anonymous users is enabled.'
    event_an_enroll_email_notify:
      type: bool
      label: "Whether users get notified by e-mail after they've enrolled anonymously."
    event_an_enroll_default_value:
      type: bool
      label: 'Whether anonymous enrollment is enabled by default for new events.'
    event_an_enroll_allow_edit:
      type: bool
      label: 'Whether event creators can edit the anonymous enrollment setting per event.'
    event_an_enroll_email_subject:
      type: label
      label: 'The subject of notification e-mails for anonymous enrollees.'
    event_an_enroll_email_body:
      type: text
      label: 'The body of notification e-mails for anonymous enrollees.'
